CREATE TABLE mytable(
   transaction_id     INTEGER  NOT NULL PRIMARY KEY 
  ,satisfaction_level VARCHAR(17) NOT NULL
);
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (1,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (2,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (3,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (4,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (5,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (6,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (7,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (8,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (9,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (10,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (11,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (12,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (13,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (14,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (15,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (16,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (17,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (18,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (19,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (20,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (21,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (22,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (23,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (24,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (25,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (26,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (27,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (28,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (29,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (30,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (31,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (32,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (33,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (34,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (35,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (36,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (37,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (38,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (39,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (40,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (41,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (42,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (43,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (44,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (45,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (46,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (47,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (48,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (49,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (50,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (51,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (52,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (53,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (54,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (55,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (56,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (57,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (58,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (59,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (60,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (61,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (62,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (63,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (64,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (65,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (66,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (67,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (68,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (69,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (70,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (71,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (72,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (73,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (74,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (75,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (76,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (77,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (78,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (79,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (80,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (81,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (82,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (83,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (84,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (85,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (86,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (87,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (88,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (89,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (90,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (91,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (92,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (93,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (94,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (95,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (96,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (97,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (98,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (99,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (100,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (101,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (102,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (103,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (104,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (105,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (106,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (107,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (108,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (109,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (110,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (111,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (112,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (113,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (114,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (115,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (116,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (117,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (118,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (119,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (120,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (121,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (122,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (123,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (124,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (125,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (126,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (127,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (128,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (129,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (130,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (131,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (132,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (133,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (134,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (135,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (136,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (137,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (138,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (139,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (140,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (141,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (142,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (143,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (144,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (145,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (146,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (147,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (148,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (149,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (150,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (151,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (152,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (153,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (154,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (155,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (156,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (157,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (158,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (159,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (160,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (161,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (162,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (163,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (164,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (165,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (166,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (167,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (168,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (169,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (170,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (171,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (172,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (173,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (174,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (175,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (176,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (177,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (178,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (179,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (180,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (181,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (182,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (183,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (184,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (185,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (186,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (187,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (188,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (189,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (190,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (191,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (192,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (193,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (194,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (195,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (196,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (197,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (198,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (199,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (200,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (201,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (202,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (203,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (204,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (205,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (206,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (207,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (208,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (209,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (210,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (211,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (212,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (213,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (214,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (215,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (216,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (217,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (218,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (219,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (220,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (221,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (222,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (223,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (224,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (225,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (226,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (227,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (228,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (229,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (230,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (231,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (232,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (233,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (234,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (235,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (236,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (237,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (238,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (239,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (240,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (241,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (242,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (243,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (244,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (245,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (246,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (247,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (248,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (249,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (250,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (251,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (252,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (253,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (254,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (255,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (256,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (257,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (258,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (259,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (260,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (261,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (262,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (263,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (264,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (265,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (266,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (267,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (268,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (269,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (270,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (271,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (272,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (273,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (274,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (275,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (276,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (277,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (278,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (279,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (280,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (281,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (282,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (283,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (284,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (285,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (286,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (287,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (288,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (289,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (290,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (291,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (292,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (293,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (294,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (295,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (296,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (297,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (298,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (299,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (300,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (301,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (302,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (303,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (304,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (305,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (306,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (307,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (308,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (309,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (310,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (311,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (312,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (313,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (314,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (315,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (316,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (317,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (318,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (319,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (320,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (321,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (322,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (323,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (324,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (325,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (326,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (327,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (328,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (329,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (330,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (331,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (332,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (333,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (334,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (335,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (336,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (337,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (338,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (339,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (340,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (341,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (342,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (343,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (344,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (345,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (346,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (347,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (348,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (349,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (350,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (351,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (352,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (353,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (354,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (355,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (356,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (357,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (358,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (359,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (360,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (361,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (362,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (363,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (364,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (365,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (366,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (367,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (368,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (369,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (370,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (371,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (372,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (373,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (374,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (375,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (376,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (377,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (378,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (379,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (380,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (381,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (382,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (383,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (384,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (385,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (386,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (387,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (388,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (389,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (390,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (391,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (392,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (393,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (394,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (395,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (396,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (397,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (398,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (399,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (400,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (401,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (402,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (403,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (404,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (405,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (406,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (407,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (408,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (409,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (410,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (411,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (412,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (413,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (414,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (415,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (416,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (417,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (418,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (419,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (420,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (421,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (422,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (423,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (424,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (425,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (426,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (427,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (428,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (429,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (430,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (431,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (432,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (433,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (434,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (435,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (436,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (437,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (438,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (439,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (440,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (441,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (442,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (443,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (444,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (445,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (446,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (447,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (448,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (449,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (450,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (451,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (452,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (453,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (454,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (455,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (456,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (457,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (458,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (459,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (460,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (461,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (462,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (463,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (464,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (465,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (466,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (467,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (468,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (469,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (470,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (471,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (472,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (473,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (474,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (475,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (476,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (477,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (478,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (479,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (480,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (481,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (482,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (483,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (484,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (485,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (486,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (487,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (488,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (489,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (490,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (491,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (492,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (493,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (494,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (495,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (496,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (497,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (498,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (499,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (500,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (501,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (502,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (503,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (504,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (505,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (506,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (507,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (508,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (509,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (510,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (511,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (512,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (513,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (514,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (515,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (516,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (517,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (518,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (519,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (520,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (521,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (522,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (523,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (524,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (525,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (526,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (527,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (528,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (529,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (530,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (531,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (532,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (533,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (534,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (535,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (536,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (537,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (538,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (539,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (540,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (541,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (542,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (543,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (544,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (545,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (546,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (547,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (548,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (549,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (550,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (551,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (552,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (553,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (554,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (555,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (556,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (557,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (558,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (559,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (560,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (561,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (562,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (563,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (564,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (565,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (566,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (567,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (568,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (569,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (570,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (571,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (572,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (573,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (574,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (575,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (576,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (577,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (578,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (579,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (580,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (581,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (582,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (583,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (584,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (585,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (586,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (587,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (588,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (589,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (590,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (591,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (592,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (593,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (594,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (595,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (596,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (597,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (598,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (599,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (600,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (601,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (602,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (603,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (604,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (605,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (606,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (607,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (608,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (609,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (610,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (611,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (612,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (613,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (614,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (615,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (616,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (617,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (618,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (619,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (620,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (621,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (622,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (623,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (624,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (625,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (626,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (627,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (628,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (629,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (630,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (631,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (632,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (633,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (634,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (635,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (636,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (637,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (638,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (639,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (640,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (641,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (642,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (643,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (644,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (645,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (646,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (647,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (648,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (649,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (650,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (651,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (652,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (653,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (654,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (655,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (656,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (657,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (658,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (659,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (660,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (661,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (662,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (663,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (664,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (665,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (666,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (667,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (668,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (669,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (670,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (671,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (672,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (673,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (674,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (675,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (676,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (677,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (678,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (679,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (680,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (681,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (682,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (683,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (684,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (685,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (686,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (687,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (688,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (689,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (690,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (691,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (692,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (693,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (694,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (695,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (696,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (697,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (698,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (699,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (700,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (701,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (702,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (703,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (704,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (705,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (706,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (707,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (708,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (709,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (710,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (711,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (712,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (713,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (714,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (715,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (716,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (717,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (718,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (719,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (720,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (721,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (722,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (723,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (724,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (725,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (726,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (727,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (728,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (729,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (730,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (731,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (732,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (733,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (734,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (735,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (736,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (737,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (738,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (739,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (740,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (741,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (742,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (743,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (744,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (745,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (746,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (747,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (748,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (749,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (750,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (751,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (752,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (753,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (754,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (755,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (756,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (757,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (758,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (759,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (760,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (761,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (762,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (763,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (764,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (765,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (766,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (767,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (768,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (769,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (770,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (771,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (772,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (773,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (774,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (775,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (776,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (777,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (778,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (779,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (780,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (781,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (782,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (783,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (784,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (785,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (786,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (787,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (788,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (789,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (790,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (791,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (792,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (793,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (794,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (795,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (796,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (797,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (798,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (799,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (800,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (801,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (802,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (803,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (804,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (805,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (806,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (807,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (808,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (809,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (810,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (811,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (812,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (813,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (814,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (815,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (816,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (817,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (818,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (819,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (820,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (821,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (822,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (823,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (824,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (825,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (826,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (827,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (828,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (829,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (830,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (831,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (832,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (833,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (834,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (835,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (836,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (837,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (838,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (839,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (840,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (841,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (842,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (843,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (844,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (845,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (846,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (847,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (848,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (849,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (850,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (851,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (852,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (853,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (854,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (855,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (856,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (857,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (858,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (859,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (860,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (861,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (862,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (863,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (864,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (865,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (866,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (867,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (868,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (869,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (870,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (871,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (872,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (873,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (874,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (875,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (876,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (877,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (878,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (879,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (880,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (881,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (882,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (883,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (884,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (885,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (886,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (887,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (888,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (889,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (890,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (891,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (892,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (893,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (894,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (895,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (896,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (897,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (898,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (899,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (900,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (901,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (902,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (903,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (904,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (905,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (906,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (907,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (908,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (909,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (910,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (911,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (912,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (913,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (914,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (915,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (916,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (917,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (918,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (919,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (920,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (921,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (922,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (923,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (924,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (925,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (926,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (927,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (928,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (929,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (930,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (931,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (932,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (933,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (934,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (935,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (936,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (937,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (938,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (939,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (940,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (941,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (942,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (943,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (944,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (945,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (946,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (947,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (948,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (949,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (950,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (951,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (952,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (953,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (954,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (955,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (956,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (957,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (958,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (959,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (960,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (961,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (962,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (963,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (964,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (965,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (966,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (967,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (968,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (969,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (970,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (971,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (972,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (973,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (974,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (975,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (976,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (977,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (978,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (979,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (980,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (981,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (982,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (983,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (984,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (985,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (986,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (987,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (988,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (989,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (990,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (991,'Very Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (992,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (993,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (994,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (995,'Very Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (996,'Neutral');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (997,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (998,'Satisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (999,'Dissatisfied');
INSERT INTO mytable(transaction_id,satisfaction_level) VALUES (1000,'Dissatisfied');
